name: Main pipeline

on:
  push:
    branches:
      - main

jobs:
  cache-and-install:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        id: pnpm-install
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

  codestyle:
    name: Codestyle
    runs-on: ubuntu-latest
    needs:
      - cache-and-install
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check codestyle
        run: pnpm run lint

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    needs:
      - cache-and-Install
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run unit tests
        run: pnpm run test:unit
